name: Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: fuzzylite-cache
        uses: actions/cache@v3
        with:
          path: .local/
          key: ${{ runner.os }}-build-${{ hashFiles('tools/dev/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - run: |
          make devtools && source `make venv_activate`
          nox -e lint

  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: fuzzylite-cache
        uses: actions/cache@v3
        with:
          path: .local/
          key: ${{ runner.os }}-build-${{ hashFiles('tools/dev/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build fuzzylite
        run: |
          make devtools && source `make venv_activate`
          nox -e configure build test -- build=debug coverage=on
          nox -e coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: build/debug/coveralls.json

  documentation:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0