name: Windows Build (monthly)

on:
  schedule: # monthly, first day
    - cron: 0 0 1 * *
  pull_request:
    branches: [ build/*, build-windows/* ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cxx-standard: [ 98, 11, 23 ]
        use_float: [ OFF, ON ]
        generator: [ "NMake Makefiles", "Visual Studio 17 2022" ]

    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Cache dependencies
        id: fuzzylite-cache
        uses: actions/cache@v3
        with:
          path: .local/
          key: ${{ runner.os }}-build-${{ hashFiles('tools/dev/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Building FuzzyLite
        shell: cmd
        env:
          CMAKE_GENERATOR: ${{ matrix.generator }}
        run: |
          make devtools && source `make venv_activate_windows`
          nox -- strict=on cxx_standard=${{ matrix.cxx-standard }} use_float=${{ matrix.use_float }}
